services:
  libelula:
    image: paschendale/libelula
    env_file:
      - .env
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_MAPBOX_TOKEN: ${MAPBOX_TOKEN}
    restart: always
    ports:
      - "3001:3001"